### ISSUE TITLE
missing package_data.txt on source code

### ISSUE THREAD

**Issue by thiagocrepaldi** [openai/atari-py#59]
Trying to pip install atari-py 0.23 on a python 2.7 conda environment leads to the following error:

2019-07-02T03:41:24.2303198Z   Using cached https://files.pythonhosted.org/packages/fc/a4/551d18c9178094a698aa5244ee52164914d65bedb68913d357d1033a58cc/atari-py-0.2.3.tar.gz
2019-07-02T03:41:24.4669762Z     Complete output from command python setup.py egg_info:
2019-07-02T03:41:24.4673356Z     Traceback (most recent call last):
2019-07-02T03:41:24.4674086Z       File "<string>", line 1, in <module>
2019-07-02T03:41:24.4675307Z       File "/tmp/pip-build-77t_o8/atari-py/setup.py", line 8, in <module>
2019-07-02T03:41:24.4676866Z         with open(os.path.join(os.path.dirname(__file__), 'atari_py', 'package_data.txt')) as f:
2019-07-02T03:41:24.4677641Z     IOError: [Errno 2] No such file or directory: '/tmp/pip-build-77t_o8/atari-py/atari_py/package_data.txt'

After downloading https://files.pythonhosted.org/packages/fc/a4/551d18c9178094a698aa5244ee52164914d65bedb68913d357d1033a58cc/atari-py-0.2.3.tar.gz, I confirmed that Atari_py/package_data.txt is missing

That started happening on June 28th. Was the python 2.7 wheel package removed on that date? That could explain why this started to happen: a pre compiled wheel package was no longer found for python 2.7, leading the build from source to take place.

**Comment by thiagocrepaldi** [comment]
https://github.com/openai/atari-py/archive/0.2.3.zip has atari_py/package_data.txt but https://files.pythonhosted.org/packages/fc/a4/551d18c9178094a698aa5244ee52164914d65bedb68913d357d1033a58cc/atari-py-0.2.3.tar.gz doesn't, so that is a clue on what is going on

**Comment by christopherhesse** [comment]
Oddly https://github.com/openai/atari-py/blob/master/atari_py/package_data.txt#L434 seems to include itself.

**Comment by christopherhesse** [comment]
Possibly fixed in https://github.com/openai/atari-py/pull/61

**Comment by thiagocrepaldi** [comment]
That particular error was fixed, but another one raised:

    copying atari_py/atari_roms/zaxxon.bin -> build/lib.linux-x86_64-2.7/atari_py/atari_roms
    copying atari_py/package_data.txt -> build/lib.linux-x86_64-2.7/atari_py
    creating build/lib.linux-x86_64-2.7/atari_py/tests
    copying atari_py/tests/test_smoke.py -> build/lib.linux-x86_64-2.7/atari_py/tests
    copying atari_py/tests/__init__.py -> build/lib.linux-x86_64-2.7/atari_py/tests
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-3t8kZq/atari-py/setup.py", line 47, in <module>
        tests_require=['nose2']
      File "/home/ubuntu/anaconda-envs/cntk-py27/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/ubuntu/anaconda-envs/cntk-py27/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/ubuntu/anaconda-envs/cntk-py27/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/ubuntu/anaconda-envs/cntk-py27/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/command/install.py", line 61, in run
      File "/home/ubuntu/anaconda-envs/cntk-py27/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/home/ubuntu/anaconda-envs/cntk-py27/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/ubuntu/anaconda-envs/cntk-py27/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/ubuntu/anaconda-envs/cntk-py27/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/home/ubuntu/anaconda-envs/cntk-py27/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/ubuntu/anaconda-envs/cntk-py27/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-3t8kZq/atari-py/setup.py", line 20, in run
        os.makedirs(cwd, exist_ok=True)
    TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

**Comment by christopherhesse** [comment]
That's almost certainly my fault, I didn't realize python 2.7 didn't have that.  If you change the line to be `if not os.path.exists(cwd): os.makedirs(cwd)`, does it work?  If we want to support python 2.7 it seems like it should be in the tests.  Please file a new issue for this
