### ISSUE TITLE
Cannot install atari-py on Linux + Python 2.7 env

### ISSUE THREAD

**Issue by thiagocrepaldi** [openai/atari-py#63]
**Steps to reproduce:**
```bash
conda create -n py27 python=2.7
conda activate py27
pip install atari-py
```
**Expected:**
atari-py gets installed on Ubuntu 16.04 x86_64 within a conda python 2.7 environment

**Actual:**
```bash
    creating build/lib.linux-x86_64-2.7/atari_py/tests
    copying atari_py/tests/test_smoke.py -> build/lib.linux-x86_64-2.7/atari_py/tests
    copying atari_py/tests/__init__.py -> build/lib.linux-x86_64-2.7/atari_py/tests
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-hKIyhH/atari-py/setup.py", line 47, in <module>
        tests_require=['nose2']
      File "/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/miniconda3/envs/py27/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/miniconda3/envs/py27/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/miniconda3/envs/py27/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/miniconda3/envs/py27/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/miniconda3/envs/py27/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/miniconda3/envs/py27/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/miniconda3/envs/py27/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/miniconda3/envs/py27/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/miniconda3/envs/py27/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/miniconda3/envs/py27/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-hKIyhH/atari-py/setup.py", line 20, in run
        os.makedirs(cwd, exist_ok=True)
    TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
    ----------------------------------------
ERROR: Command "/miniconda3/envs/py27/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-hKIyhH/atari-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wThLEi/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-hKIyhH/atari-py/
```

**Comment by christopherhesse** [comment]
That's almost certainly my fault, I didn't realize python 2.7 didn't have that.  If you change the line to be `if not os.path.exists(cwd): os.makedirs(cwd)`, does it work?  If we want to support python 2.7 it seems like it should be in the tests.

**Comment by thiagocrepaldi** [comment]
It does work. As I had to fork the project and test the fix, I also created a PR to get it working faster: https://github.com/openai/atari-py/pull/64

**Comment by christopherhesse** [comment]
Thanks!
