### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by Sc07713** [openai/atari-py#69]
Can someone tell me what is going wrong here?

```
(rainbow) C:\Users\s#####\Documents\github\Rainbow>python main.py
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    import atari_py
  File "C:\Users\s#####\.conda\envs\rainbow\lib\site-packages\atari_py\__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "C:\Users\s#####\.conda\envs\rainbow\lib\site-packages\atari_py\ale_python_interface.py", line 18, in <module>
    'ale_interface/ale_c.dll'))
  File "C:\Users\s#####\.conda\envs\rainbow\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\s#####\.conda\envs\rainbow\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

**Comment by storercd** [comment]
Looks like you are running this on Windows, judging from the file system; I had a similar experience on a Windows machine and also read that it is not compatible with Windows.  Try Mac or Linux for a different experience.

**Comment by storercd** [comment]
For posterity: a workaround is posted on Github and can be installed in place of the existing atari; this worked for me for multiple Windows machines.
pip install --no-index -f https://github.com/Kojoley/atari-py/releases atari_py
https://stackoverflow.com/questions/42605769/openai-gym-atari-on-windows
