### ISSUE TITLE
OSError: [WinError 126] Cannot find the specified module

### ISSUE THREAD

**Issue by s-larson** [openai/atari-py#70]
Trying to get Pong to work following https://github.com/dhruvp/atari-pong/blob/master/me_pong.py. I run **env = gym.make('Pong-v0')** and this error appears:

```
env = gym.make('Pong-v0')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\GuCa\PycharmProjects\Pong\venv\lib\site-packages\gym\envs\registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "C:\Users\GuCa\PycharmProjects\Pong\venv\lib\site-packages\gym\envs\registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "C:\Users\GuCa\PycharmProjects\Pong\venv\lib\site-packages\gym\envs\registration.py", line 72, in make
    cls = load(self.entry_point)
  File "C:\Users\GuCa\PycharmProjects\Pong\venv\lib\site-packages\gym\envs\registration.py", line 17, in load
    mod = importlib.import_module(mod_name)
  File "C:\Users\GuCa\AppData\Local\Programs\Python\Python37-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\GuCa\PycharmProjects\Pong\venv\lib\site-packages\gym\envs\atari\__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\GuCa\PycharmProjects\Pong\venv\lib\site-packages\gym\envs\atari\atari_env.py", line 9, in <module>
    import atari_py
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\GuCa\PycharmProjects\Pong\venv\lib\site-packages\atari_py\__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\GuCa\PycharmProjects\Pong\venv\lib\site-packages\atari_py\ale_python_interface.py", line 18, in <module>
    'ale_interface/ale_c.dll'))
  File "C:\Users\GuCa\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\GuCa\AppData\Local\Programs\Python\Python37-32\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] Cannot find the specified module

```
No errors when running **pip install "gym[atari]"** inside "...\projectFolder\atari.py"
Any suggestions? Please explain like i'm five

**Comment by s-larson** [comment]
SOLVED

I solved this by installing an older version of Python (3.6) and then installing gym
